# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf34639c76346a58f569f49411f7c5b8b27bb3ba03a8f135269b0cd25d60845f6f2002746f99deccce4eab7705724deaa08f0ffc28ec43e798cd3f57c237149

test:
  secret_key_base: 521abad8078cf61f03927a09ad219ac933089cab623ab6b663c849663a7c5a4ea439b621e9ca9e5d11e35bd54a71d52ec071c243b810698e3b02f784feb02ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
